name: PyChecks

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:

    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        # Install a specific version of uv.
        version: "0.6.8"
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: uv sync --all-extras --dev

    - name: Run Tests
      run: |
        if [ -d tests ]; then
          uv run pytest --cov=validate --cov-report=term
        else
          echo "No tests found"
        fi
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:

      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          # Install a specific version of uv.
          version: "0.6.8"
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Run Linting
        run: |
          uv run pylint $(git ls-files '*.py') --fail-under=8.0 --recursive=y --enable=W